services:
  sldl:
    ports:
    - "127.0.0.1:48721:48721"
    build:
      context: .
    environment:
      - TZ=Etc/GMT # Specify timezone from TZ Database name found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- PUID=1000 # recommended if running docker on linux host, see main README Docker setup instructions
      #- PGID=1000 # recommended if running docker on linux host, see main README Docker setup instructions
    volumes:
      - ./config:/config
      - ./data:/data
